"""Namespace ``Microsoft.Scripting.Hosting`` -- generated by revit-stubgen 0.1.0 (net462). Do not edit."""
import builtins
import enum
import typing
import typing_extensions
import _dotnet
import Microsoft.Scripting
import Microsoft.Scripting.Runtime
import Microsoft.Scripting.Hosting
from . import Configuration as Configuration
from . import Providers as Providers
from . import Shell as Shell

T = typing.TypeVar("T")
TOther = typing.TypeVar("TOther")
TResult = typing.TypeVar("TResult")
TService = typing.TypeVar("TService")
TTarget = typing.TypeVar("TTarget")
__all__ = ["CompiledCode", "DocumentationOperations", "ErrorListener", "ErrorSinkProxyListener", "ExceptionOperations", "LanguageSetup", "MemberDoc", "MemberKind", "ObjectOperations", "OverloadDoc", "ParameterDoc", "ParameterFlags", "ScriptEngine", "ScriptHost", "ScriptIO", "ScriptRuntime", "ScriptRuntimeSetup", "ScriptScope", "ScriptSource", "TokenCategorizer", "Configuration", "Providers", "Shell"]

class CompiledCode:
    """Hosting API counterpart for CompiledCode.ScriptCode."""
    @builtins.property
    def DefaultScope(self) -> Microsoft.Scripting.Hosting.ScriptScope:
        """Default scope for this code."""
    @builtins.property
    def Engine(self) -> Microsoft.Scripting.Hosting.ScriptEngine:
        """Engine that compiled this code."""
    @typing.overload
    def Execute(self) -> typing.Any:
        """Executes code in a default scope."""
    @typing.overload
    def Execute(self, scope: Microsoft.Scripting.Hosting.ScriptScope) -> typing.Any:
        """Execute code within a given scope and returns the result."""
    @typing.overload
    def ExecuteAndWrap(self) -> typing.Any:
        """Executes the code in an empty scope.
        Returns an ObjectHandle wrapping the resulting value of running the code.
        """
    @typing.overload
    def ExecuteAndWrap(self, scope: Microsoft.Scripting.Hosting.ScriptScope) -> typing.Any:
        """Executes the code in the specified scope.
        Returns an ObjectHandle wrapping the resulting value of running the code.
        """
    def InitializeLifetimeService(self) -> typing.Any:
        ...

class DocumentationOperations:
    """Provides documentation against live objects for use in a REPL window."""
    def GetMembers(self, value: typing.Any) -> typing.Collection[Microsoft.Scripting.Hosting.MemberDoc]:
        """Gets the available members defined on the provided object."""
    def GetOverloads(self, value: typing.Any) -> typing.Collection[Microsoft.Scripting.Hosting.OverloadDoc]:
        """Gets the overloads available for the provided object if it is invokable."""
    def InitializeLifetimeService(self) -> typing.Any:
        ...

class ErrorListener:
    """The host can use this class to track for errors reported during script parsing and compilation.
    Hosting API counterpart for ErrorSink.
    """
    def ErrorReported(self, source: Microsoft.Scripting.Hosting.ScriptSource, message: str, span: Microsoft.Scripting.SourceSpan, errorCode: int, severity: Microsoft.Scripting.Severity) -> None:
        ...
    def InitializeLifetimeService(self) -> typing.Any:
        ...

class ErrorSinkProxyListener(Microsoft.Scripting.Hosting.ErrorListener):
    """Bridges ErrorListener and ErrorSink. It provides the reverse functionality as ErrorSinkProxyListener"""
    def ErrorReported(self, source: Microsoft.Scripting.Hosting.ScriptSource, message: str, span: Microsoft.Scripting.SourceSpan, errorCode: int, severity: Microsoft.Scripting.Severity) -> None:
        ...
    def __init__(self, errorSink: Microsoft.Scripting.ErrorSink) -> None:
        ...

class ExceptionOperations:
    @typing.overload
    def FormatException(self, exception: Exception) -> str:
        ...
    @typing.overload
    def FormatException(self, exception: typing.Any) -> str:
        ...
    @typing.overload
    def GetExceptionMessage(self, exception: Exception) -> typing.Tuple[str, str]:
        ...
    @typing.overload
    def GetExceptionMessage(self, exception: typing.Any) -> typing.Tuple[str, str]:
        ...
    @typing.overload
    def GetStackFrames(self, exception: Exception) -> typing.List[Microsoft.Scripting.Runtime.DynamicStackFrame]:
        ...
    @typing.overload
    def GetStackFrames(self, exception: typing.Any) -> typing.List[Microsoft.Scripting.Runtime.DynamicStackFrame]:
        ...
    @typing.overload
    def HandleException(self, exception: Exception) -> bool:
        ...
    @typing.overload
    def HandleException(self, exception: typing.Any) -> bool:
        ...
    def InitializeLifetimeService(self) -> typing.Any:
        ...

class LanguageSetup:
    """Stores information needed to setup a language"""
    @builtins.property
    def DisplayName(self) -> str:
        """Display name of the language. If empty, it will be set to the first
        name in the Names list.
        """
    @DisplayName.setter
    def DisplayName(self, value: str) -> None: ...
    @builtins.property
    def ExceptionDetail(self) -> bool:
        ...
    @ExceptionDetail.setter
    def ExceptionDetail(self, value: bool) -> None: ...
    @builtins.property
    def FileExtensions(self) -> typing.List[str]:
        """Remarks:
            Case-insensitive file extension, optionally starts with a dot.
        """
    @builtins.property
    @typing_extensions.deprecated('This option is ignored')
    def InterpretedMode(self) -> bool:
        ...
    @InterpretedMode.setter
    def InterpretedMode(self, value: bool) -> None: ...
    @builtins.property
    def Names(self) -> typing.List[str]:
        """Remarks:
            Case-insensitive language names.
        """
    @builtins.property
    @typing_extensions.deprecated('Use Options["NoAdaptiveCompilation"] instead.')
    def NoAdaptiveCompilation(self) -> bool:
        ...
    @NoAdaptiveCompilation.setter
    def NoAdaptiveCompilation(self, value: bool) -> None: ...
    @builtins.property
    def Options(self) -> typing.Dict[str, typing.Any]:
        """Remarks:
            Option names are case-sensitive.
        """
    @builtins.property
    @typing_extensions.deprecated('Use Options["PerfStats"] instead.')
    def PerfStats(self) -> bool:
        ...
    @PerfStats.setter
    def PerfStats(self, value: bool) -> None: ...
    @builtins.property
    def TypeName(self) -> str:
        """The assembly qualified type name of the language provider"""
    @TypeName.setter
    def TypeName(self, value: str) -> None: ...
    def GetOption(self, name: str, defaultValue: T) -> T:
        """Gets an option as a strongly typed value."""
    @typing.overload
    def __init__(self, typeName: str) -> None:
        """Creates a new LanguageSetup

        Args:
            typeName: assembly qualified type name of the language
                provider
        """
    @typing.overload
    def __init__(self, typeName: str, displayName: str) -> None:
        """Creates a new LanguageSetup with the provided options
        TODO: remove this overload?
        """
    @typing.overload
    def __init__(self, typeName: str, displayName: str, names: typing.Iterable[str], fileExtensions: typing.Iterable[str]) -> None:
        """Creates a new LanguageSetup with the provided options"""

class MemberDoc:
    """Provides documentation about a member in a live object."""
    @builtins.property
    def Kind(self) -> Microsoft.Scripting.Hosting.MemberKind:
        """The kind of the member if it's known."""
    @builtins.property
    def Name(self) -> str:
        """The name of the member"""
    def __init__(self, name: str, kind: Microsoft.Scripting.Hosting.MemberKind) -> None:
        ...

class MemberKind(enum.IntEnum):
    """Specifies the type of member."""
    None_ = 0
    Class = 1
    Delegate = 2
    Enum = 3
    Event = 4
    Field = 5
    Function = 6
    Module = 7
    Property = 8
    Constant = 9
    EnumMember = 10
    Instance = 11
    Method = 12
    Namespace = 13

class ObjectOperations:
    """ObjectOperations provide a large catalogue of object operations such as member access, conversions,
    indexing, and things like addition. There are several introspection and tool support services available
    for more advanced hosts.

    You get ObjectOperation instances from ScriptEngine, and they are bound to their engines for the semantics
    of the operations. There is a default instance of ObjectOperations you can share across all uses of the
    engine. However, very advanced hosts can create new instances.
    """
    @builtins.property
    def Engine(self) -> Microsoft.Scripting.Hosting.ScriptEngine:
        ...
    def Add(self, self_: typing.Any, other: typing.Any) -> typing.Any:
        """Performs addition on the specified targets and returns the result. Throws an exception
        if the operation cannot be performed.
        """
    def BitwiseAnd(self, self_: typing.Any, other: typing.Any) -> typing.Any:
        """Performs a bitwise-and of the two operands. Throws an exception if the operation
        cannot be performed.
        """
    def BitwiseOr(self, self_: typing.Any, other: typing.Any) -> typing.Any:
        """Performs a bitwise-or of the two operands. Throws an exception if the operation
        cannot be performed.
        """
    @typing.overload
    def ContainsMember(self, obj: typing.Any, name: str) -> bool:
        """Returns true if the object has a member named name, false if the member does not exist."""
    @typing.overload
    def ContainsMember(self, obj: typing.Any, name: str, ignoreCase: bool) -> bool:
        """Returns true if the object has a member named name, false if the member does not exist."""
    @typing.overload
    def ConvertTo(self, obj: typing.Any, type: type) -> typing.Any:
        """Converts the object obj to the type type. The conversion will be explicit or implicit depending on
        what the langauge prefers.
        """
    @typing.overload
    def ConvertTo(self, obj: typing.Any) -> T:
        """Converts the object obj to the type T. The conversion will be explicit or implicit depending on
        what the langauge prefers.
        """
    def CreateInstance(self, obj: typing.Any, *parameters: typing.Any) -> typing.Any:
        """Creates a new instance from the provided object using the given parameters, and returns the result."""
    def Divide(self, self_: typing.Any, other: typing.Any) -> typing.Any:
        """Divides the first object by the second object. Throws an exception
        if the operation cannot be performed.
        """
    @typing.overload
    def DoOperation(self, operation: typing.Any, target: typing.Any) -> typing.Any:
        """Performs a generic unary operation on the specified target and returns the result."""
    @typing.overload
    def DoOperation(self, operation: typing.Any, target: typing.Any, other: typing.Any) -> typing.Any:
        """Performs the generic binary operation on the specified targets and returns the result."""
    @typing.overload
    def DoOperation(self, operation: typing.Any, target: TTarget) -> TResult:
        """Performs a generic unary operation on the strongly typed target and returns the value as the specified type"""
    @typing.overload
    def DoOperation(self, operation: typing.Any, target: TTarget, other: TOther) -> TResult:
        """Peforms the generic binary operation on the specified strongly typed targets and returns
        the strongly typed result.
        """
    def Equal(self, self_: typing.Any, other: typing.Any) -> bool:
        """Compares the two objects and returns true if the left object is equal to the right object.
        Throws an exception if the comparison cannot be performed.
        """
    def ExclusiveOr(self, self_: typing.Any, other: typing.Any) -> typing.Any:
        """Performs a exclusive-or of the two operands. Throws an exception if the operation
        cannot be performed.
        """
    @typing.overload
    def ExplicitConvertTo(self, obj: typing.Any, type: type) -> typing.Any:
        """Converts the object obj to the type type including explicit conversions which may lose information."""
    @typing.overload
    def ExplicitConvertTo(self, obj: typing.Any) -> T:
        """Converts the object obj to the type T including explicit conversions which may lose information."""
    def Format(self, obj: typing.Any) -> str:
        """Returns a string representation of the object in a language specific object display format."""
    def GetCallSignatures(self, obj: typing.Any) -> typing.List[str]:
        """Returns a list of signatures applicable for calling the specified object in a form displayable to the user."""
    @typing_extensions.deprecated('Use Format method instead.')
    def GetCodeRepresentation(self, obj: typing.Any) -> str:
        """Returns a string which describes the object as it appears in source code"""
    def GetDocumentation(self, obj: typing.Any) -> str:
        """Returns a string providing documentation for the specified object."""
    @typing.overload
    def GetMember(self, obj: typing.Any, name: str) -> typing.Any:
        """Gets the member name from the object obj. Throws an exception if the member does not exist or is write-only."""
    @typing.overload
    def GetMember(self, obj: typing.Any, name: str, ignoreCase: bool) -> typing.Any:
        """Gets the member name from the object obj. Throws an exception if the member does not exist or is write-only."""
    def GetMemberNames(self, obj: typing.Any) -> typing.List[str]:
        """Returns a list of strings which contain the known members of the object."""
    def GreaterThan(self, self_: typing.Any, other: typing.Any) -> bool:
        """Compares the two objects and returns true if the left object is greater than the right object.
        Throws an exception if hte comparison cannot be performed.
        """
    def GreaterThanOrEqual(self, self_: typing.Any, other: typing.Any) -> bool:
        """Compares the two objects and returns true if the left object is greater than or equal to the right object.
        Throws an exception if hte comparison cannot be performed.
        """
    @typing.overload
    def ImplicitConvertTo(self, obj: typing.Any, type: type) -> typing.Any:
        """Converts the object obj to the type type including implicit conversions."""
    @typing.overload
    def ImplicitConvertTo(self, obj: typing.Any) -> T:
        """Converts the object obj to the type T including implicit conversions."""
    def InitializeLifetimeService(self) -> typing.Any:
        ...
    def Invoke(self, obj: typing.Any, *parameters: typing.Any) -> typing.Any:
        """Invokes the provided object with the given parameters and returns the result.

        The prefered way of calling objects is to convert the object to a strongly typed delegate
        using the ConvertTo methods and then invoking that delegate.
        """
    def InvokeMember(self, obj: typing.Any, memberName: str, *parameters: typing.Any) -> typing.Any:
        """Invokes a member on the provided object with the given parameters and returns the result."""
    def IsCallable(self, obj: typing.Any) -> bool:
        """Returns true if the object can be called, false if it cannot.

        Even if an object is callable Call may still fail if an incorrect number of arguments or type of arguments are provided.
        """
    def LeftShift(self, self_: typing.Any, other: typing.Any) -> typing.Any:
        """Shifts the left object left by the right object. Throws an exception if the
        operation cannot be performed.
        """
    def LessThan(self, self_: typing.Any, other: typing.Any) -> bool:
        """Compares the two objects and returns true if the left object is less than the right object.
        Throws an exception if hte comparison cannot be performed.
        """
    def LessThanOrEqual(self, self_: typing.Any, other: typing.Any) -> bool:
        """Compares the two objects and returns true if the left object is less than or equal to the right object.
        Throws an exception if hte comparison cannot be performed.
        """
    def Modulo(self, self_: typing.Any, other: typing.Any) -> typing.Any:
        """Performs modulus of the 1st object by the second object. Throws an exception
        if the operation cannot be performed.
        """
    def Multiply(self, self_: typing.Any, other: typing.Any) -> typing.Any:
        """Multiplies the two objects. Throws an exception
        if the operation cannot be performed.
        """
    def NotEqual(self, self_: typing.Any, other: typing.Any) -> bool:
        """Compares the two objects and returns true if the left object is not equal to the right object.
        Throws an exception if hte comparison cannot be performed.
        """
    def Power(self, self_: typing.Any, other: typing.Any) -> typing.Any:
        """Raises the first object to the power of the second object. Throws an exception
        if the operation cannot be performed.
        """
    @typing.overload
    def RemoveMember(self, obj: typing.Any, name: str) -> None:
        """Removes the member name from the object obj."""
    @typing.overload
    def RemoveMember(self, obj: typing.Any, name: str, ignoreCase: bool) -> None:
        """Removes the member name from the object obj."""
    def RightShift(self, self_: typing.Any, other: typing.Any) -> typing.Any:
        """Shifts the left object right by the right object. Throws an exception if the
        operation cannot be performed.
        """
    @typing.overload
    def SetMember(self, obj: typing.Any, name: str, value: typing.Any) -> None:
        """Sets the member name on object obj to value."""
    @typing.overload
    def SetMember(self, obj: typing.Any, name: str, value: typing.Any, ignoreCase: bool) -> None:
        """Sets the member name on object obj to value."""
    @typing.overload
    def SetMember(self, obj: typing.Any, name: str, value: T) -> None:
        """Sets the member name on object obj to value. This overload can be used to avoid
        boxing and casting of strongly typed members.
        """
    @typing.overload
    def SetMember(self, obj: typing.Any, name: str, value: T, ignoreCase: bool) -> None:
        """Sets the member name on object obj to value. This overload can be used to avoid
        boxing and casting of strongly typed members.
        """
    def Subtract(self, self_: typing.Any, other: typing.Any) -> typing.Any:
        """Performs subtraction on the specified targets and returns the result. Throws an exception
        if the operation cannot be performed.
        """
    @typing.overload
    def TryConvertTo(self, obj: typing.Any, type: type) -> typing.Tuple[bool, typing.Any]:
        """Converts the object obj to the type type. Returns true if the value can be converted, false if it cannot.

        The conversion will be explicit or implicit depending on what the langauge prefers.
        """
    @typing.overload
    def TryConvertTo(self, obj: typing.Any) -> typing.Tuple[bool, T]:
        """Converts the object obj to the type T. Returns true if the value can be converted, false if it cannot.

        The conversion will be explicit or implicit depending on what the langauge prefers.
        """
    @typing.overload
    def TryExplicitConvertTo(self, obj: typing.Any, type: type) -> typing.Tuple[bool, typing.Any]:
        """Converts the object obj to the type type including explicit conversions which may lose information.

        Returns true if the value can be converted, false if it cannot.
        """
    @typing.overload
    def TryExplicitConvertTo(self, obj: typing.Any) -> typing.Tuple[bool, T]:
        """Converts the object obj to the type T including explicit conversions which may lose information.

        Returns true if the value can be converted, false if it cannot.
        """
    @typing.overload
    def TryGetMember(self, obj: typing.Any, name: str) -> typing.Tuple[bool, typing.Any]:
        """Gets the member name from the object obj. Returns true if the member is successfully retrieved and
        stores the value in the value out param.
        """
    @typing.overload
    def TryGetMember(self, obj: typing.Any, name: str, ignoreCase: bool) -> typing.Tuple[bool, typing.Any]:
        """Gets the member name from the object obj. Returns true if the member is successfully retrieved and
        stores the value in the value out param.
        """
    @typing.overload
    def TryImplicitConvertTo(self, obj: typing.Any, type: type) -> typing.Tuple[bool, typing.Any]:
        """Converts the object obj to the type type including implicit conversions.

        Returns true if the value can be converted, false if it cannot.
        """
    @typing.overload
    def TryImplicitConvertTo(self, obj: typing.Any) -> typing.Tuple[bool, T]:
        """Converts the object obj to the type T including implicit conversions.

        Returns true if the value can be converted, false if it cannot.
        """
    def Unwrap(self, obj: typing.Any) -> T:
        """Unwraps the remote object and converts it into the specified type before
        returning it.
        """

class OverloadDoc:
    """Provides documentation for a single overload of an invokable object."""
    @builtins.property
    def Documentation(self) -> str:
        """The documentation for the overload or null if no documentation is available."""
    @builtins.property
    def Name(self) -> str:
        """The name of the invokable object."""
    @builtins.property
    def Parameters(self) -> typing.Collection[Microsoft.Scripting.Hosting.ParameterDoc]:
        """The parameters for the invokable object."""
    @builtins.property
    def ReturnParameter(self) -> Microsoft.Scripting.Hosting.ParameterDoc:
        """Information about the return value."""
    @typing.overload
    def __init__(self, name: str, documentation: str, parameters: typing.Collection[Microsoft.Scripting.Hosting.ParameterDoc]) -> None:
        ...
    @typing.overload
    def __init__(self, name: str, documentation: str, parameters: typing.Collection[Microsoft.Scripting.Hosting.ParameterDoc], returnParameter: Microsoft.Scripting.Hosting.ParameterDoc) -> None:
        ...

class ParameterDoc:
    """Provides documentation for a single parameter."""
    @builtins.property
    def Documentation(self) -> str:
        """Gets the documentation string for this parameter or null if no documentation is available."""
    @builtins.property
    def Flags(self) -> Microsoft.Scripting.Hosting.ParameterFlags:
        """Provides addition information about the parameter such as if it's a parameter array."""
    @builtins.property
    def Name(self) -> str:
        """The name of the parameter"""
    @builtins.property
    def TypeName(self) -> str:
        """The type name of the parameter or null if no type information is available."""
    @typing.overload
    def __init__(self, name: str) -> None:
        ...
    @typing.overload
    def __init__(self, name: str, paramFlags: Microsoft.Scripting.Hosting.ParameterFlags) -> None:
        ...
    @typing.overload
    def __init__(self, name: str, typeName: str) -> None:
        ...
    @typing.overload
    def __init__(self, name: str, typeName: str, documentation: str) -> None:
        ...
    @typing.overload
    def __init__(self, name: str, typeName: str, documentation: str, paramFlags: Microsoft.Scripting.Hosting.ParameterFlags) -> None:
        ...

class ParameterFlags(enum.IntFlag):
    """Indications extra information about a parameter such as if it's a parameter array."""
    None_ = 0
    ParamsArray = 1
    ParamsDict = 2

class ScriptEngine:
    """Represents a language in Hosting API.
    Hosting API counterpart for ScriptEngine.LanguageContext.
    """
    @builtins.property
    def LanguageVersion(self) -> typing.Any:
        """This property returns the engine's version as a string. The format is language-dependent."""
    @builtins.property
    def Operations(self) -> Microsoft.Scripting.Hosting.ObjectOperations:
        """Returns a default ObjectOperations for the engine.

        Because an ObjectOperations object caches rules for the types of
        objects and operations it processes, using the default ObjectOperations for
        many objects could degrade the caching benefits. Eventually the cache for
        some operations could degrade to a point where ObjectOperations stops caching and
        does a full search for an implementation of the requested operation for the given objects.

        Another reason to create a new ObjectOperations instance is to have it bound
        to the specific view of a ScriptScope. Languages may attach per-language
        behavior to a ScriptScope which would alter how the operations are performed.

        For simple hosting situations, this is sufficient behavior.
        """
    @builtins.property
    def Runtime(self) -> Microsoft.Scripting.Hosting.ScriptRuntime:
        """This property returns the ScriptRuntime for the context in which this engine executes."""
    @builtins.property
    def Setup(self) -> Microsoft.Scripting.Hosting.LanguageSetup:
        """This property returns readon-only LanguageOptions this engine is using.

        Remarks:
            The values are determined during runtime initialization and read-only afterwards.
            You can change the settings via a configuration file or explicitly using ScriptRuntimeSetup class.
        """
    @typing.overload
    def CreateOperations(self) -> Microsoft.Scripting.Hosting.ObjectOperations:
        """Returns a new ObjectOperations object. See the Operations property for why you might want to call this."""
    @typing.overload
    def CreateOperations(self, scope: Microsoft.Scripting.Hosting.ScriptScope) -> Microsoft.Scripting.Hosting.ObjectOperations:
        """Returns a new ObjectOperations object that inherits any semantics particular to the provided ScriptScope.

        See the Operations property for why you might want to call this.
        """
    @typing.overload
    def CreateScope(self) -> Microsoft.Scripting.Hosting.ScriptScope:
        """Creates a new ScriptScope using the default storage container"""
    @typing.overload
    def CreateScope(self, dictionary: typing.Dict[str, typing.Any]) -> Microsoft.Scripting.Hosting.ScriptScope:
        """Creates a new ScriptScope whose storage contains the provided dictionary of objects

        Accesses to the ScriptScope will turn into get,set, and delete members against this dictionary
        """
    @typing.overload
    def CreateScope(self, storage: typing.Any) -> Microsoft.Scripting.Hosting.ScriptScope:
        """Creates a new ScriptScope whose storage is an arbitrary object.

        Accesses to the ScriptScope will turn into get, set, and delete members against the object.
        """
    @typing.overload
    def CreateScriptSource(self, content: typing.Any) -> Microsoft.Scripting.Hosting.ScriptSource:
        """This method returns a ScriptSource object from a System.CodeDom.CodeObject.
        This is a factory method for creating a ScriptSources with this language binding.

        The expected CodeDom support is extremely minimal for syntax-independent expression of semantics.

        Languages may do more, but hosts should only expect CodeMemberMethod support,
        and only sub nodes consisting of the following:
        CodeSnippetStatement
        CodeSnippetExpression
        CodePrimitiveExpression
        CodeMethodInvokeExpression
        CodeExpressionStatement (for holding MethodInvoke)
        """
    @typing.overload
    def CreateScriptSource(self, content: typing.Any, path: str) -> Microsoft.Scripting.Hosting.ScriptSource:
        """This method returns a ScriptSource object from a System.CodeDom.CodeObject.
        This is a factory method for creating a ScriptSources with this language binding.

        The expected CodeDom support is extremely minimal for syntax-independent expression of semantics.

        Languages may do more, but hosts should only expect CodeMemberMethod support,
        and only sub nodes consisting of the following:
        CodeSnippetStatement
        CodeSnippetExpression
        CodePrimitiveExpression
        CodeMethodInvokeExpression
        CodeExpressionStatement (for holding MethodInvoke)
        """
    @typing.overload
    def CreateScriptSource(self, content: typing.Any, kind: Microsoft.Scripting.SourceCodeKind) -> Microsoft.Scripting.Hosting.ScriptSource:
        """This method returns a ScriptSource object from a System.CodeDom.CodeObject.
        This is a factory method for creating a ScriptSources with this language binding.

        The expected CodeDom support is extremely minimal for syntax-independent expression of semantics.

        Languages may do more, but hosts should only expect CodeMemberMethod support,
        and only sub nodes consisting of the following:
        CodeSnippetStatement
        CodeSnippetExpression
        CodePrimitiveExpression
        CodeMethodInvokeExpression
        CodeExpressionStatement (for holding MethodInvoke)
        """
    @typing.overload
    def CreateScriptSource(self, content: Microsoft.Scripting.StreamContentProvider, path: str) -> Microsoft.Scripting.Hosting.ScriptSource:
        """These methods return ScriptSource objects from stream contents with the current engine as the language binding.

        The default SourceCodeKind is File.

        The encoding defaults to the default encoding of the language.
        """
    @typing.overload
    def CreateScriptSource(self, content: typing.Any, path: str, kind: Microsoft.Scripting.SourceCodeKind) -> Microsoft.Scripting.Hosting.ScriptSource:
        """This method returns a ScriptSource object from a System.CodeDom.CodeObject.
        This is a factory method for creating a ScriptSources with this language binding.

        The expected CodeDom support is extremely minimal for syntax-independent expression of semantics.

        Languages may do more, but hosts should only expect CodeMemberMethod support,
        and only sub nodes consisting of the following:
        CodeSnippetStatement
        CodeSnippetExpression
        CodePrimitiveExpression
        CodeMethodInvokeExpression
        CodeExpressionStatement (for holding MethodInvoke)
        """
    @typing.overload
    def CreateScriptSource(self, content: Microsoft.Scripting.StreamContentProvider, path: str, encoding: typing.Any) -> Microsoft.Scripting.Hosting.ScriptSource:
        """These methods return ScriptSource objects from stream contents with the current engine as the language binding.

        The default SourceCodeKind is File.
        """
    @typing.overload
    def CreateScriptSource(self, contentProvider: Microsoft.Scripting.TextContentProvider, path: str, kind: Microsoft.Scripting.SourceCodeKind) -> Microsoft.Scripting.Hosting.ScriptSource:
        """This method returns a ScriptSource with the content provider supplied with the current engine as the language binding.

        This helper lets you own the content provider so that you can implement a stream over internal host data structures, such as an editor's text representation.
        """
    @typing.overload
    def CreateScriptSource(self, content: Microsoft.Scripting.StreamContentProvider, path: str, encoding: typing.Any, kind: Microsoft.Scripting.SourceCodeKind) -> Microsoft.Scripting.Hosting.ScriptSource:
        """These methods return ScriptSource objects from stream contents with the current engine as the language binding.

        The encoding defaults to Encoding.Default.
        """
    @typing.overload
    def CreateScriptSourceFromFile(self, path: str) -> Microsoft.Scripting.Hosting.ScriptSource:
        """Return a ScriptSource object from file contents with the current engine as the language binding.

        The path's extension does NOT have to be in ScriptRuntime.GetRegisteredFileExtensions
        or map to this language engine with ScriptRuntime.GetEngineByFileExtension.

        The default SourceCodeKind is File.

        The ScriptSource's Path property will be the path argument.

        The encoding defaults to the default encoding of the language.
        """
    @typing.overload
    def CreateScriptSourceFromFile(self, path: str, encoding: typing.Any) -> Microsoft.Scripting.Hosting.ScriptSource:
        """Return a ScriptSource object from file contents with the current engine as the language binding.

        The path's extension does NOT have to be in ScriptRuntime.GetRegisteredFileExtensions
        or map to this language engine with ScriptRuntime.GetEngineByFileExtension.

        The default SourceCodeKind is File.

        The ScriptSource's Path property will be the path argument.
        """
    @typing.overload
    def CreateScriptSourceFromFile(self, path: str, encoding: typing.Any, kind: Microsoft.Scripting.SourceCodeKind) -> Microsoft.Scripting.Hosting.ScriptSource:
        """Return a ScriptSource object from file contents with the current engine as the language binding.

        The path's extension does NOT have to be in ScriptRuntime.GetRegisteredFileExtensions
        or map to this language engine with ScriptRuntime.GetEngineByFileExtension.

        The ScriptSource's Path property will be the path argument.
        """
    @typing.overload
    def CreateScriptSourceFromString(self, expression: str) -> Microsoft.Scripting.Hosting.ScriptSource:
        """Return a ScriptSource object from string contents with the current engine as the language binding.

        The default SourceCodeKind is AutoDetect.

        The ScriptSource's Path property defaults to `null`.
        """
    @typing.overload
    def CreateScriptSourceFromString(self, code: str, kind: Microsoft.Scripting.SourceCodeKind) -> Microsoft.Scripting.Hosting.ScriptSource:
        """Return a ScriptSource object from string contents with the current engine as the language binding.

        The ScriptSource's Path property defaults to `null`.
        """
    @typing.overload
    def CreateScriptSourceFromString(self, expression: str, path: str) -> Microsoft.Scripting.Hosting.ScriptSource:
        """Return a ScriptSource object from string contents with the current engine as the language binding.

        The default SourceCodeKind is AutoDetect.
        """
    @typing.overload
    def CreateScriptSourceFromString(self, code: str, path: str, kind: Microsoft.Scripting.SourceCodeKind) -> Microsoft.Scripting.Hosting.ScriptSource:
        """Return a ScriptSource object from string contents. These are helpers for creating ScriptSources' with the right language binding."""
    @typing.overload
    def Execute(self, expression: str) -> typing.Any:
        """Executes an expression. The execution is not bound to any particular scope.

        Raises:
            NotSupportedException: The engine doesn't support code execution.
            ArgumentNullException: expression is a `null` reference.
        """
    @typing.overload
    def Execute(self, expression: str, scope: Microsoft.Scripting.Hosting.ScriptScope) -> typing.Any:
        """Executes an expression within the specified scope.

        Raises:
            NotSupportedException: The engine doesn't support code execution.
            ArgumentNullException: expression is a `null` reference.
            ArgumentNullException: scope is a `null` reference.
        """
    @typing.overload
    def ExecuteAndWrap(self, expression: str) -> typing.Any:
        """Executes the code in an empty scope.
        Returns an ObjectHandle wrapping the resulting value of running the code.
        """
    @typing.overload
    def ExecuteAndWrap(self, expression: str, scope: Microsoft.Scripting.Hosting.ScriptScope) -> typing.Any:
        """Executes the expression in the specified scope and return a result.
        Returns an ObjectHandle wrapping the resulting value of running the code.
        """
    @typing.overload
    def ExecuteFile(self, path: str) -> Microsoft.Scripting.Hosting.ScriptScope:
        """Executes content of the specified file in a new scope and returns that scope.

        Raises:
            NotSupportedException: The engine doesn't support code execution.
            ArgumentNullException: path is a `null` reference.
        """
    @typing.overload
    def ExecuteFile(self, path: str, scope: Microsoft.Scripting.Hosting.ScriptScope) -> Microsoft.Scripting.Hosting.ScriptScope:
        """Executes content of the specified file against the given scope.

        Returns:
            The scope.

        Raises:
            NotSupportedException: The engine doesn't support code execution.
            ArgumentNullException: path is a `null` reference.
            ArgumentNullException: scope is a `null` reference.
        """
    @typing.overload
    def GetCompilerOptions(self) -> Microsoft.Scripting.CompilerOptions:
        ...
    @typing.overload
    def GetCompilerOptions(self, scope: Microsoft.Scripting.Hosting.ScriptScope) -> Microsoft.Scripting.CompilerOptions:
        ...
    def GetScope(self, path: str) -> Microsoft.Scripting.Hosting.ScriptScope:
        """This method returns the ScriptScope in which a ScriptSource of given path was executed.

        The ScriptSource.Path property is the key to finding the ScriptScope. Hosts need
        to make sure they create a ScriptSource and set its Path property appropriately.

        GetScope is primarily useful for tools that need to map files to their execution scopes. For example,
        an editor and interpreter tool might run a file Foo that imports or requires a file Bar.

        The editor's user might later open the file Bar and want to execute expressions in its context.
        The tool would need to find Bar's ScriptScope for setting the appropriate context in its interpreter window.
        This method helps with this scenario.
        """
    def GetSearchPaths(self) -> typing.Collection[str]:
        """Gets the search paths used by the engine for loading files when a script wants
        to import or require another file of code.
        """
    def GetService(self, *args: typing.Any) -> TService:
        """This method returns a language-specific service.

        It provides a point of extensibility for a language implementation
        to offer more functionality than the standard engine members discussed here.

        Commonly available services include:
        TokenCategorizer
        Provides standardized tokenization of source code
        ExceptionOperations
        Provides formatting of exception objects.
        DocumentationProvidera
        Provides documentation for live object.
        """
    def InitializeLifetimeService(self) -> typing.Any:
        ...
    def SetSearchPaths(self, paths: typing.Collection[str]) -> None:
        """Sets the search paths used by the engine for loading files when a script wants
        to import or require another file of code.

        Raises:
            NotSupportedException: The language doesn't allow to set search paths.
        """

class ScriptHost:
    """ScriptHost is collocated with ScriptRuntime in the same app-domain.
    The host can implement a derived class to consume some notifications and/or
    customize operations like TryGetSourceUnit,ResolveSourceUnit, etc.

    The areguments to the the constructor of the derived class are specified in ScriptRuntimeSetup
    instance that enters ScriptRuntime initialization.

    If the host is remote with respect to DLR (i.e. also with respect to ScriptHost)
    and needs to access objects living in its app-domain it can pass MarshalByRefObject
    as an argument to its ScriptHost subclass constructor.
    """
    @builtins.property
    def PlatformAdaptationLayer(self) -> Microsoft.Scripting.PlatformAdaptationLayer:
        ...
    @builtins.property
    def Runtime(self) -> Microsoft.Scripting.Hosting.ScriptRuntime:
        ...
    def InitializeLifetimeService(self) -> typing.Any:
        ...
    def __init__(self) -> None:
        ...

class ScriptIO:
    """Provides host-redirectable IO streams used by DLR languages for default IO."""
    @builtins.property
    def ErrorEncoding(self) -> typing.Any:
        ...
    @builtins.property
    def ErrorStream(self) -> typing.Any:
        ...
    @builtins.property
    def ErrorWriter(self) -> typing.Any:
        ...
    @builtins.property
    def InputEncoding(self) -> typing.Any:
        ...
    @builtins.property
    def InputReader(self) -> typing.Any:
        ...
    @builtins.property
    def InputStream(self) -> typing.Any:
        ...
    @builtins.property
    def OutputEncoding(self) -> typing.Any:
        ...
    @builtins.property
    def OutputStream(self) -> typing.Any:
        ...
    @builtins.property
    def OutputWriter(self) -> typing.Any:
        ...
    def InitializeLifetimeService(self) -> typing.Any:
        ...
    def RedirectToConsole(self) -> None:
        ...
    def SetErrorOutput(self, stream: typing.Any, encoding: typing.Any) -> None:
        ...
    @typing.overload
    def SetInput(self, stream: typing.Any, encoding: typing.Any) -> None:
        ...
    @typing.overload
    def SetInput(self, stream: typing.Any, reader: typing.Any, encoding: typing.Any) -> None:
        ...
    def SetOutput(self, stream: typing.Any, encoding: typing.Any) -> None:
        """Used if the host stores the output as binary data.

        Args:
            stream: Binary stream to write data to.
            encoding: Encoding used to convert textual data written to the output by the script.
        """

class ScriptRuntime:
    """Represents a Dynamic Language Runtime in Hosting API.
    Hosting API counterpart for ScriptDomainManager.
    """
    @builtins.property
    def Globals(self) -> Microsoft.Scripting.Hosting.ScriptScope:
        """This property returns the "global object" or name bindings of the ScriptRuntime as a ScriptScope.

        You can set the globals scope, which you might do if you created a ScriptScope with an
        IAttributesCollection so that your host could late bind names.
        """
    @Globals.setter
    def Globals(self, value: Microsoft.Scripting.Hosting.ScriptScope) -> None: ...
    @builtins.property
    def Host(self) -> Microsoft.Scripting.Hosting.ScriptHost:
        ...
    @builtins.property
    def IO(self) -> Microsoft.Scripting.Hosting.ScriptIO:
        ...
    @builtins.property
    def Operations(self) -> Microsoft.Scripting.Hosting.ObjectOperations:
        ...
    @builtins.property
    def Setup(self) -> Microsoft.Scripting.Hosting.ScriptRuntimeSetup:
        ...
    @builtins.staticmethod
    def CreateFromConfiguration() -> Microsoft.Scripting.Hosting.ScriptRuntime:
        """Creates a new runtime with languages set up according to the current application configuration
        (using System.Configuration).
        """
    def CreateOperations(self) -> Microsoft.Scripting.Hosting.ObjectOperations:
        ...
    @builtins.staticmethod
    def CreateRemote(domain: typing.Any, setup: Microsoft.Scripting.Hosting.ScriptRuntimeSetup) -> Microsoft.Scripting.Hosting.ScriptRuntime:
        """Creates ScriptRuntime in the current app-domain and initialized according to the the specified settings.
        Creates an instance of host class specified in the setup and associates it with the created runtime.
        Both Runtime and ScriptHost are collocated in the specified app-domain.
        """
    @typing.overload
    def CreateScope(self) -> Microsoft.Scripting.Hosting.ScriptScope:
        ...
    @typing.overload
    def CreateScope(self, languageId: str) -> Microsoft.Scripting.Hosting.ScriptScope:
        ...
    @typing.overload
    def CreateScope(self, storage: typing.Any) -> Microsoft.Scripting.Hosting.ScriptScope:
        ...
    @typing.overload
    def CreateScope(self, dictionary: typing.Dict[str, typing.Any]) -> Microsoft.Scripting.Hosting.ScriptScope:
        ...
    @typing.overload
    def CreateScope(self, languageId: str, storage: typing.Any) -> Microsoft.Scripting.Hosting.ScriptScope:
        ...
    @typing.overload
    def CreateScope(self, languageId: str, storage: typing.Dict[str, typing.Any]) -> Microsoft.Scripting.Hosting.ScriptScope:
        ...
    def ExecuteFile(self, path: str) -> Microsoft.Scripting.Hosting.ScriptScope:
        """Raises:
            ArgumentException: path is empty, contains one or more of the invalid characters defined in GetInvalidPathChars or doesn't have an extension.
        """
    def GetEngine(self, languageName: str) -> Microsoft.Scripting.Hosting.ScriptEngine:
        """Gets engine for the specified language."""
    def GetEngineByFileExtension(self, fileExtension: str) -> Microsoft.Scripting.Hosting.ScriptEngine:
        """Raises:
            ArgumentException: 
            ArgumentNullException: 
        """
    def GetEngineByTypeName(self, assemblyQualifiedTypeName: str) -> Microsoft.Scripting.Hosting.ScriptEngine:
        ...
    def InitializeLifetimeService(self) -> typing.Any:
        ...
    def LoadAssembly(self, assembly: typing.Any) -> None:
        """This method walks the assembly's namespaces and name bindings to ScriptRuntime.Globals
        to represent the types available in the assembly. Each top-level namespace name gets
        bound in Globals to a dynamic object representing the namespace. Within each top-level
        namespace object, nested namespace names are bound to dynamic objects representing each
        tier of nested namespaces. When this method encounters the same namespace-qualified name,
        it merges names together objects representing the namespaces.
        """
    def Shutdown(self) -> None:
        ...
    def TryGetEngine(self, languageName: str) -> typing.Tuple[bool, Microsoft.Scripting.Hosting.ScriptEngine]:
        ...
    def TryGetEngineByFileExtension(self, fileExtension: str) -> typing.Tuple[bool, Microsoft.Scripting.Hosting.ScriptEngine]:
        ...
    def UseFile(self, path: str) -> Microsoft.Scripting.Hosting.ScriptScope:
        """Raises:
            ArgumentNullException: path is null
            ArgumentException: file extension does not map to language engine
            InvalidOperationException: language does not have any search paths
            FileNotFoundException: file does exist in language's search path
        """
    def __init__(self, setup: Microsoft.Scripting.Hosting.ScriptRuntimeSetup) -> None:
        """Creates ScriptRuntime in the current app-domain and initialized according to the the specified settings.
        Creates an instance of host class specified in the setup and associates it with the created runtime.
        Both Runtime and ScriptHost are collocated in the current app-domain.
        """

class ScriptRuntimeSetup:
    """Stores information needed to setup a ScriptRuntime"""
    @builtins.property
    def DebugMode(self) -> bool:
        """Indicates that the script runtime is in debug mode.
        This means:

        1) Symbols are emitted for debuggable methods (methods associated with SourceUnit).
        2) Debuggable methods are emitted to non-collectable types (this is due to CLR limitations on dynamic method debugging).
        3) JIT optimization is disabled for all methods
        4) Languages may disable optimizations based on this value.
        """
    @DebugMode.setter
    def DebugMode(self, value: bool) -> None: ...
    @builtins.property
    def HostArguments(self) -> typing.List[typing.Any]:
        """Arguments passed to the host type when it is constructed"""
    @HostArguments.setter
    def HostArguments(self, value: typing.List[typing.Any]) -> None: ...
    @builtins.property
    def HostType(self) -> type:
        """Can be any derived class of ScriptHost. When set, it allows the
        host to override certain methods to control behavior of the runtime
        """
    @HostType.setter
    def HostType(self, value: type) -> None: ...
    @builtins.property
    def LanguageSetups(self) -> typing.List[Microsoft.Scripting.Hosting.LanguageSetup]:
        """The list of language setup information for languages to load into
        the runtime
        """
    @builtins.property
    def Options(self) -> typing.Dict[str, typing.Any]:
        """Remarks:
            Option names are case-sensitive.
        """
    @builtins.property
    def PrivateBinding(self) -> bool:
        """Ignore CLR visibility checks"""
    @PrivateBinding.setter
    def PrivateBinding(self, value: bool) -> None: ...
    @typing.overload
    @builtins.staticmethod
    def ReadConfiguration() -> Microsoft.Scripting.Hosting.ScriptRuntimeSetup:
        """Reads setup from .NET configuration system (.config files).
        If there is no configuration available returns an empty setup.
        """
    @typing.overload
    @builtins.staticmethod
    def ReadConfiguration(configFileStream: typing.Any) -> Microsoft.Scripting.Hosting.ScriptRuntimeSetup:
        """Reads setup from a specified XML stream."""
    @typing.overload
    @builtins.staticmethod
    def ReadConfiguration(configFilePath: str) -> Microsoft.Scripting.Hosting.ScriptRuntimeSetup:
        """Reads setup from a specified XML file."""
    def __init__(self) -> None:
        ...

class ScriptScope:
    """A ScriptScope is a unit of execution for code. It consists of a global Scope which
    all code executes in. A ScriptScope can have an arbitrary initializer and arbitrary
    reloader.

    ScriptScope is not thread safe. Host should either lock when multiple threads could
    access the same module or should make a copy for each thread.

    Hosting API counterpart for ScriptScope.Scope.
    """
    @builtins.property
    def Engine(self) -> Microsoft.Scripting.Hosting.ScriptEngine:
        """Gets an engine for the language associated with this scope.
        Returns invariant engine if the scope is language agnostic.
        """
    def ContainsVariable(self, name: str) -> bool:
        """Determines if this context or any outer scope contains the defined name.

        Raises:
            ArgumentNullException: name is a `null` reference.
        """
    def GetItems(self) -> typing.Iterable[typing.Tuple[str, typing.Any]]:
        """Gets an array of variable names and their values stored in the scope."""
    def GetVariable(self, name: str) -> typing.Any:
        """Gets a value stored in the scope under the given name.

        Raises:
            MissingMemberException: The specified name is not defined in the scope.
            ArgumentNullException: name is a `null` reference.
        """
    def GetVariableHandle(self, name: str) -> typing.Any:
        """Gets a handle for a value stored in the scope under the given name.

        Raises:
            MissingMemberException: The specified name is not defined in the scope.
            ArgumentNullException: name is a `null` reference.
        """
    def GetVariableNames(self) -> typing.Iterable[str]:
        """Gets a list of variable names stored in the scope."""
    def InitializeLifetimeService(self) -> typing.Any:
        ...
    def RemoveVariable(self, name: str) -> bool:
        """Removes the variable of the given name from this scope.

        Returns:
            `true` if the value existed in the scope before it has been removed.

        Raises:
            ArgumentNullException: name is a `null` reference.
        """
    def SetVariable(self, name: str, value: typing.Any) -> None:
        """Sets the name to the specified value.

        Raises:
            ArgumentNullException: name is a `null` reference.
        """
    def TryGetVariable(self, name: str) -> typing.Tuple[bool, typing.Any]:
        """Tries to get a value stored in the scope under the given name.

        Raises:
            ArgumentNullException: name is a `null` reference.
        """
    def TryGetVariableHandle(self, name: str) -> typing.Tuple[bool, typing.Any]:
        """Tries to get a handle for a value stored in the scope under the given name.
        Returns `true` if there is such name, `false` otherwise.

        Raises:
            ArgumentNullException: name is a `null` reference.
        """

class ScriptSource:
    """Hosting counterpart for ScriptSource.SourceUnit."""
    @builtins.property
    def Engine(self) -> Microsoft.Scripting.Hosting.ScriptEngine:
        ...
    @builtins.property
    def Kind(self) -> Microsoft.Scripting.SourceCodeKind:
        ...
    @builtins.property
    def Path(self) -> str:
        """Identification of the source unit. Assigned by the host.
        The format and semantics is host dependent (could be a path on file system or URL).
        `null` for anonymous script source.
        Cannot be an empty string.
        """
    @typing.overload
    def Compile(self) -> Microsoft.Scripting.Hosting.CompiledCode:
        """Compile the ScriptSource into CompileCode object that can be executed
        repeatedly in its default scope or in other scopes without having to recompile the code.

        Raises:
            SyntaxErrorException: Code cannot be compiled.
        """
    @typing.overload
    def Compile(self, errorListener: Microsoft.Scripting.Hosting.ErrorListener) -> Microsoft.Scripting.Hosting.CompiledCode:
        """Remarks:
            Errors are reported to the specified listener.
            Returns `null` if the parser cannot compile the code due to errors.
        """
    @typing.overload
    def Compile(self, compilerOptions: Microsoft.Scripting.CompilerOptions) -> Microsoft.Scripting.Hosting.CompiledCode:
        """Remarks:
            Errors are reported to the specified listener.
            Returns `null` if the parser cannot compile the code due to error(s).
        """
    @typing.overload
    def Compile(self, compilerOptions: Microsoft.Scripting.CompilerOptions, errorListener: Microsoft.Scripting.Hosting.ErrorListener) -> Microsoft.Scripting.Hosting.CompiledCode:
        """Remarks:
            Errors are reported to the specified listener.
            Returns `null` if the parser cannot compile the code due to error(s).
        """
    def DetectEncoding(self) -> typing.Any:
        """Detects the encoding of the content.

        Remarks:
            Note that the default encoding specified when the script source is created could be overridden by
            an encoding that is found in the content preamble (Unicode BOM or a language specific encoding preamble).
            In that case the preamble encoding is returned. Otherwise, the default encoding is returned.

        Returns:
            An encoding that is used by the reader of the script source to transcode its content to Unicode text.
            `Null` if the content is already textual and no transcoding is performed.

        Raises:
            IOException: An I/O error occurs.
        """
    @typing.overload
    def Execute(self) -> typing.Any:
        """Executes the source code. The execution is not bound to any particular scope."""
    @typing.overload
    def Execute(self, scope: Microsoft.Scripting.Hosting.ScriptScope) -> typing.Any:
        """Executes the code in the specified scope.
        Returns an object that is the resulting value of running the code.

        When the ScriptSource is a file or statement, the engine decides what is
        an appropriate value to return. Some languages return the value produced
        by the last expression or statement, but languages that are not expression
        based may return null.

        Raises:
            SyntaxErrorException: Code cannot be compiled.
        """
    @typing.overload
    def ExecuteAndWrap(self) -> typing.Any:
        """Executes the code in an empty scope.
        Returns an ObjectHandle wrapping the resulting value of running the code.
        """
    @typing.overload
    def ExecuteAndWrap(self, scope: Microsoft.Scripting.Hosting.ScriptScope) -> typing.Any:
        """Executes the code in the specified scope.
        Returns an ObjectHandle wrapping the resulting value of running the code.
        """
    def ExecuteProgram(self) -> int:
        """Runs a specified code as if it was a program launched from OS command shell.
        and returns a process exit code indicating the success or error condition
        of executing the code.

        Exact behavior depends on the language. Some languages have a dedicated "exit" exception that
        carries the exit code, in which case the exception is cought and the exit code is returned.
        The default behavior returns the result of program's execution converted to an integer
        using a language specific conversion.

        Raises:
            SyntaxErrorException: Code cannot be compiled.
        """
    def GetCode(self) -> str:
        """Gets script source content.

        Remarks:
            The result includes language specific preambles (e.g. "#coding:UTF-8" encoding preamble recognized by Ruby),
            but not the preamble defined by the content encoding (e.g. BOM).
            The entire content of the source unit is encoded by single encoding (if it is read from binary stream).

        Returns:
            Entire content.

        Raises:
            IOException: An I/O error occurs.
        """
    def GetCodeLine(self, line: int) -> str:
        """Reads a specified line.

        Remarks:
            Which character sequences are considered line separators is language specific.
            If language doesn't specify otherwise "\\r", "\\n", "\\r\\n" are recognized line separators.

        Args:
            line: 1-based line number.

        Returns:
            Line content. Line separator is not included.

        Raises:
            IOException: An I/O error occurs.
        """
    def GetCodeLines(self, start: int, count: int) -> typing.List[str]:
        """Reads specified range of lines (or less) from the source unit.

        Remarks:
            Which character sequences are considered line separators is language specific.
            If language doesn't specify otherwise "\\r", "\\n", "\\r\\n" are recognized line separators.

        Args:
            start: 1-based number of the first line to fetch.
            count: The number of lines to fetch.

        Raises:
            IOException: An I/O error occurs.
        """
    @typing.overload
    def GetCodeProperties(self) -> Microsoft.Scripting.ScriptCodeParseResult:
        ...
    @typing.overload
    def GetCodeProperties(self, options: Microsoft.Scripting.CompilerOptions) -> Microsoft.Scripting.ScriptCodeParseResult:
        ...
    def GetReader(self) -> Microsoft.Scripting.SourceCodeReader:
        ...
    def InitializeLifetimeService(self) -> typing.Any:
        ...
    @typing.overload
    def MapLine(self, line: int) -> int:
        ...
    @typing.overload
    def MapLine(self, span: Microsoft.Scripting.SourceSpan) -> Microsoft.Scripting.SourceSpan:
        ...
    @typing.overload
    def MapLine(self, location: Microsoft.Scripting.SourceLocation) -> Microsoft.Scripting.SourceLocation:
        ...
    def MapLinetoFile(self, line: int) -> str:
        ...

class TokenCategorizer:
    @builtins.property
    def CurrentPosition(self) -> Microsoft.Scripting.SourceLocation:
        """The current startLocation of the scanner."""
    @builtins.property
    def CurrentState(self) -> typing.Any:
        """The current internal state of the scanner."""
    @builtins.property
    def ErrorSink(self) -> Microsoft.Scripting.ErrorSink:
        ...
    @ErrorSink.setter
    def ErrorSink(self, value: Microsoft.Scripting.ErrorSink) -> None: ...
    @builtins.property
    def IsRestartable(self) -> bool:
        ...
    def Initialize(self, state: typing.Any, scriptSource: Microsoft.Scripting.Hosting.ScriptSource, initialLocation: Microsoft.Scripting.SourceLocation) -> None:
        ...
    def InitializeLifetimeService(self) -> typing.Any:
        ...
    def ReadToken(self) -> Microsoft.Scripting.TokenInfo:
        """Move the tokenizer past the next token and return its category.

        Returns:
            The token information associated with the token just scanned.
        """
    def ReadTokens(self, characterCount: int) -> typing.Iterable[Microsoft.Scripting.TokenInfo]:
        """Get all tokens over a block of the stream.

        Remarks:
            The scanner should return full tokens. If startLocation + length lands in the middle of a token, the full token
            should be returned.

        Args:
            characterCount: Tokens are read until at least given amount of characters is read or the stream ends.

        Returns:
            A enumeration of tokens.
        """
    def SkipToken(self) -> bool:
        """Move the tokenizer past the next token.

        Returns:
            `False` if the end of stream has been reached, `true` otherwise.
        """
    def SkipTokens(self, characterCount: int) -> bool:
        """Scan from startLocation to at least startLocation + length.

        Remarks:
            This method is used to determine state at arbitrary startLocation.

        Args:
            characterCount: Tokens are read until at least given amount of characters is read or the stream ends.

        Returns:
            `False` if the end of stream has been reached, `true` otherwise.
        """
